#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App_112GW.Droid.Resource", IsApplication=true)]

namespace App_112GW.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::App_112GW.Droid.Resource.String.library_name;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.EnterFromLeft = global::App_112GW.Droid.Resource.Animation.EnterFromLeft;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.EnterFromRight = global::App_112GW.Droid.Resource.Animation.EnterFromRight;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.ExitToLeft = global::App_112GW.Droid.Resource.Animation.ExitToLeft;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.ExitToRight = global::App_112GW.Droid.Resource.Animation.ExitToRight;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.alpha = global::App_112GW.Droid.Resource.Attribute.alpha;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.coordinatorLayoutStyle = global::App_112GW.Droid.Resource.Attribute.coordinatorLayoutStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.font = global::App_112GW.Droid.Resource.Attribute.font;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontProviderAuthority = global::App_112GW.Droid.Resource.Attribute.fontProviderAuthority;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontProviderCerts = global::App_112GW.Droid.Resource.Attribute.fontProviderCerts;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontProviderFetchStrategy = global::App_112GW.Droid.Resource.Attribute.fontProviderFetchStrategy;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontProviderFetchTimeout = global::App_112GW.Droid.Resource.Attribute.fontProviderFetchTimeout;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontProviderPackage = global::App_112GW.Droid.Resource.Attribute.fontProviderPackage;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontProviderQuery = global::App_112GW.Droid.Resource.Attribute.fontProviderQuery;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontStyle = global::App_112GW.Droid.Resource.Attribute.fontStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontVariationSettings = global::App_112GW.Droid.Resource.Attribute.fontVariationSettings;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.fontWeight = global::App_112GW.Droid.Resource.Attribute.fontWeight;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.keylines = global::App_112GW.Droid.Resource.Attribute.keylines;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.layout_anchor = global::App_112GW.Droid.Resource.Attribute.layout_anchor;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.layout_anchorGravity = global::App_112GW.Droid.Resource.Attribute.layout_anchorGravity;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.layout_behavior = global::App_112GW.Droid.Resource.Attribute.layout_behavior;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.layout_dodgeInsetEdges = global::App_112GW.Droid.Resource.Attribute.layout_dodgeInsetEdges;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.layout_insetEdge = global::App_112GW.Droid.Resource.Attribute.layout_insetEdge;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.layout_keyline = global::App_112GW.Droid.Resource.Attribute.layout_keyline;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.statusBarBackground = global::App_112GW.Droid.Resource.Attribute.statusBarBackground;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.ttcIndex = global::App_112GW.Droid.Resource.Attribute.ttcIndex;
			global::Xamarin.Forms.Platform.Android.Resource.Color.notification_action_color_filter = global::App_112GW.Droid.Resource.Color.notification_action_color_filter;
			global::Xamarin.Forms.Platform.Android.Resource.Color.notification_icon_bg_color = global::App_112GW.Droid.Resource.Color.notification_icon_bg_color;
			global::Xamarin.Forms.Platform.Android.Resource.Color.notification_material_background_media_default_color = global::App_112GW.Droid.Resource.Color.notification_material_background_media_default_color;
			global::Xamarin.Forms.Platform.Android.Resource.Color.primary_text_default_material_dark = global::App_112GW.Droid.Resource.Color.primary_text_default_material_dark;
			global::Xamarin.Forms.Platform.Android.Resource.Color.ripple_material_light = global::App_112GW.Droid.Resource.Color.ripple_material_light;
			global::Xamarin.Forms.Platform.Android.Resource.Color.secondary_text_default_material_dark = global::App_112GW.Droid.Resource.Color.secondary_text_default_material_dark;
			global::Xamarin.Forms.Platform.Android.Resource.Color.secondary_text_default_material_light = global::App_112GW.Droid.Resource.Color.secondary_text_default_material_light;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.compat_button_inset_horizontal_material = global::App_112GW.Droid.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.compat_button_inset_vertical_material = global::App_112GW.Droid.Resource.Dimension.compat_button_inset_vertical_material;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.compat_button_padding_horizontal_material = global::App_112GW.Droid.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.compat_button_padding_vertical_material = global::App_112GW.Droid.Resource.Dimension.compat_button_padding_vertical_material;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.compat_control_corner_material = global::App_112GW.Droid.Resource.Dimension.compat_control_corner_material;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.compat_notification_large_icon_max_height = global::App_112GW.Droid.Resource.Dimension.compat_notification_large_icon_max_height;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.compat_notification_large_icon_max_width = global::App_112GW.Droid.Resource.Dimension.compat_notification_large_icon_max_width;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_action_icon_size = global::App_112GW.Droid.Resource.Dimension.notification_action_icon_size;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_action_text_size = global::App_112GW.Droid.Resource.Dimension.notification_action_text_size;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_big_circle_margin = global::App_112GW.Droid.Resource.Dimension.notification_big_circle_margin;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_content_margin_start = global::App_112GW.Droid.Resource.Dimension.notification_content_margin_start;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_large_icon_height = global::App_112GW.Droid.Resource.Dimension.notification_large_icon_height;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_large_icon_width = global::App_112GW.Droid.Resource.Dimension.notification_large_icon_width;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_main_column_padding_top = global::App_112GW.Droid.Resource.Dimension.notification_main_column_padding_top;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_media_narrow_margin = global::App_112GW.Droid.Resource.Dimension.notification_media_narrow_margin;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_right_icon_size = global::App_112GW.Droid.Resource.Dimension.notification_right_icon_size;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_right_side_padding_top = global::App_112GW.Droid.Resource.Dimension.notification_right_side_padding_top;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_small_icon_background_padding = global::App_112GW.Droid.Resource.Dimension.notification_small_icon_background_padding;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_small_icon_size_as_large = global::App_112GW.Droid.Resource.Dimension.notification_small_icon_size_as_large;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_subtext_size = global::App_112GW.Droid.Resource.Dimension.notification_subtext_size;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_top_pad = global::App_112GW.Droid.Resource.Dimension.notification_top_pad;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.notification_top_pad_large_text = global::App_112GW.Droid.Resource.Dimension.notification_top_pad_large_text;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.subtitle_corner_radius = global::App_112GW.Droid.Resource.Dimension.subtitle_corner_radius;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.subtitle_outline_width = global::App_112GW.Droid.Resource.Dimension.subtitle_outline_width;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.subtitle_shadow_offset = global::App_112GW.Droid.Resource.Dimension.subtitle_shadow_offset;
			global::Xamarin.Forms.Platform.Android.Resource.Dimension.subtitle_shadow_radius = global::App_112GW.Droid.Resource.Dimension.subtitle_shadow_radius;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_action_background = global::App_112GW.Droid.Resource.Drawable.notification_action_background;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_bg = global::App_112GW.Droid.Resource.Drawable.notification_bg;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_bg_low = global::App_112GW.Droid.Resource.Drawable.notification_bg_low;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_bg_low_normal = global::App_112GW.Droid.Resource.Drawable.notification_bg_low_normal;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_bg_low_pressed = global::App_112GW.Droid.Resource.Drawable.notification_bg_low_pressed;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_bg_normal = global::App_112GW.Droid.Resource.Drawable.notification_bg_normal;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_bg_normal_pressed = global::App_112GW.Droid.Resource.Drawable.notification_bg_normal_pressed;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_icon_background = global::App_112GW.Droid.Resource.Drawable.notification_icon_background;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_template_icon_bg = global::App_112GW.Droid.Resource.Drawable.notification_template_icon_bg;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_template_icon_low_bg = global::App_112GW.Droid.Resource.Drawable.notification_template_icon_low_bg;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notification_tile_bg = global::App_112GW.Droid.Resource.Drawable.notification_tile_bg;
			global::Xamarin.Forms.Platform.Android.Resource.Drawable.notify_panel_notification_icon_bg = global::App_112GW.Droid.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Xamarin.Forms.Platform.Android.Resource.Id.action0 = global::App_112GW.Droid.Resource.Id.action0;
			global::Xamarin.Forms.Platform.Android.Resource.Id.action_container = global::App_112GW.Droid.Resource.Id.action_container;
			global::Xamarin.Forms.Platform.Android.Resource.Id.action_divider = global::App_112GW.Droid.Resource.Id.action_divider;
			global::Xamarin.Forms.Platform.Android.Resource.Id.action_image = global::App_112GW.Droid.Resource.Id.action_image;
			global::Xamarin.Forms.Platform.Android.Resource.Id.action_text = global::App_112GW.Droid.Resource.Id.action_text;
			global::Xamarin.Forms.Platform.Android.Resource.Id.actions = global::App_112GW.Droid.Resource.Id.actions;
			global::Xamarin.Forms.Platform.Android.Resource.Id.all = global::App_112GW.Droid.Resource.Id.all;
			global::Xamarin.Forms.Platform.Android.Resource.Id.async = global::App_112GW.Droid.Resource.Id.async;
			global::Xamarin.Forms.Platform.Android.Resource.Id.blocking = global::App_112GW.Droid.Resource.Id.blocking;
			global::Xamarin.Forms.Platform.Android.Resource.Id.bottom = global::App_112GW.Droid.Resource.Id.bottom;
			global::Xamarin.Forms.Platform.Android.Resource.Id.bottomtab_navarea = global::App_112GW.Droid.Resource.Id.bottomtab_navarea;
			global::Xamarin.Forms.Platform.Android.Resource.Id.bottomtab_tabbar = global::App_112GW.Droid.Resource.Id.bottomtab_tabbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.cancel_action = global::App_112GW.Droid.Resource.Id.cancel_action;
			global::Xamarin.Forms.Platform.Android.Resource.Id.center = global::App_112GW.Droid.Resource.Id.center;
			global::Xamarin.Forms.Platform.Android.Resource.Id.center_horizontal = global::App_112GW.Droid.Resource.Id.center_horizontal;
			global::Xamarin.Forms.Platform.Android.Resource.Id.center_vertical = global::App_112GW.Droid.Resource.Id.center_vertical;
			global::Xamarin.Forms.Platform.Android.Resource.Id.chronometer = global::App_112GW.Droid.Resource.Id.chronometer;
			global::Xamarin.Forms.Platform.Android.Resource.Id.clip_horizontal = global::App_112GW.Droid.Resource.Id.clip_horizontal;
			global::Xamarin.Forms.Platform.Android.Resource.Id.clip_vertical = global::App_112GW.Droid.Resource.Id.clip_vertical;
			global::Xamarin.Forms.Platform.Android.Resource.Id.end = global::App_112GW.Droid.Resource.Id.end;
			global::Xamarin.Forms.Platform.Android.Resource.Id.end_padder = global::App_112GW.Droid.Resource.Id.end_padder;
			global::Xamarin.Forms.Platform.Android.Resource.Id.fill = global::App_112GW.Droid.Resource.Id.fill;
			global::Xamarin.Forms.Platform.Android.Resource.Id.fill_horizontal = global::App_112GW.Droid.Resource.Id.fill_horizontal;
			global::Xamarin.Forms.Platform.Android.Resource.Id.fill_vertical = global::App_112GW.Droid.Resource.Id.fill_vertical;
			global::Xamarin.Forms.Platform.Android.Resource.Id.flyoutcontent_appbar = global::App_112GW.Droid.Resource.Id.flyoutcontent_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.flyoutcontent_recycler = global::App_112GW.Droid.Resource.Id.flyoutcontent_recycler;
			global::Xamarin.Forms.Platform.Android.Resource.Id.forever = global::App_112GW.Droid.Resource.Id.forever;
			global::Xamarin.Forms.Platform.Android.Resource.Id.ghost_view = global::App_112GW.Droid.Resource.Id.ghost_view;
			global::Xamarin.Forms.Platform.Android.Resource.Id.icon = global::App_112GW.Droid.Resource.Id.icon;
			global::Xamarin.Forms.Platform.Android.Resource.Id.icon_group = global::App_112GW.Droid.Resource.Id.icon_group;
			global::Xamarin.Forms.Platform.Android.Resource.Id.info = global::App_112GW.Droid.Resource.Id.info;
			global::Xamarin.Forms.Platform.Android.Resource.Id.italic = global::App_112GW.Droid.Resource.Id.italic;
			global::Xamarin.Forms.Platform.Android.Resource.Id.left = global::App_112GW.Droid.Resource.Id.left;
			global::Xamarin.Forms.Platform.Android.Resource.Id.line1 = global::App_112GW.Droid.Resource.Id.line1;
			global::Xamarin.Forms.Platform.Android.Resource.Id.line3 = global::App_112GW.Droid.Resource.Id.line3;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_appbar = global::App_112GW.Droid.Resource.Id.main_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_scrollview = global::App_112GW.Droid.Resource.Id.main_scrollview;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_tablayout = global::App_112GW.Droid.Resource.Id.main_tablayout;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_toolbar = global::App_112GW.Droid.Resource.Id.main_toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.media_actions = global::App_112GW.Droid.Resource.Id.media_actions;
			global::Xamarin.Forms.Platform.Android.Resource.Id.none = global::App_112GW.Droid.Resource.Id.none;
			global::Xamarin.Forms.Platform.Android.Resource.Id.normal = global::App_112GW.Droid.Resource.Id.normal;
			global::Xamarin.Forms.Platform.Android.Resource.Id.notification_background = global::App_112GW.Droid.Resource.Id.notification_background;
			global::Xamarin.Forms.Platform.Android.Resource.Id.notification_main_column = global::App_112GW.Droid.Resource.Id.notification_main_column;
			global::Xamarin.Forms.Platform.Android.Resource.Id.notification_main_column_container = global::App_112GW.Droid.Resource.Id.notification_main_column_container;
			global::Xamarin.Forms.Platform.Android.Resource.Id.parent_matrix = global::App_112GW.Droid.Resource.Id.parent_matrix;
			global::Xamarin.Forms.Platform.Android.Resource.Id.right = global::App_112GW.Droid.Resource.Id.right;
			global::Xamarin.Forms.Platform.Android.Resource.Id.right_icon = global::App_112GW.Droid.Resource.Id.right_icon;
			global::Xamarin.Forms.Platform.Android.Resource.Id.right_side = global::App_112GW.Droid.Resource.Id.right_side;
			global::Xamarin.Forms.Platform.Android.Resource.Id.save_image_matrix = global::App_112GW.Droid.Resource.Id.save_image_matrix;
			global::Xamarin.Forms.Platform.Android.Resource.Id.save_non_transition_alpha = global::App_112GW.Droid.Resource.Id.save_non_transition_alpha;
			global::Xamarin.Forms.Platform.Android.Resource.Id.save_scale_type = global::App_112GW.Droid.Resource.Id.save_scale_type;
			global::Xamarin.Forms.Platform.Android.Resource.Id.shellcontent_appbar = global::App_112GW.Droid.Resource.Id.shellcontent_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.shellcontent_scrollview = global::App_112GW.Droid.Resource.Id.shellcontent_scrollview;
			global::Xamarin.Forms.Platform.Android.Resource.Id.shellcontent_toolbar = global::App_112GW.Droid.Resource.Id.shellcontent_toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.start = global::App_112GW.Droid.Resource.Id.start;
			global::Xamarin.Forms.Platform.Android.Resource.Id.status_bar_latest_event_content = global::App_112GW.Droid.Resource.Id.status_bar_latest_event_content;
			global::Xamarin.Forms.Platform.Android.Resource.Id.tag_transition_group = global::App_112GW.Droid.Resource.Id.tag_transition_group;
			global::Xamarin.Forms.Platform.Android.Resource.Id.tag_unhandled_key_event_manager = global::App_112GW.Droid.Resource.Id.tag_unhandled_key_event_manager;
			global::Xamarin.Forms.Platform.Android.Resource.Id.tag_unhandled_key_listeners = global::App_112GW.Droid.Resource.Id.tag_unhandled_key_listeners;
			global::Xamarin.Forms.Platform.Android.Resource.Id.text = global::App_112GW.Droid.Resource.Id.text;
			global::Xamarin.Forms.Platform.Android.Resource.Id.text2 = global::App_112GW.Droid.Resource.Id.text2;
			global::Xamarin.Forms.Platform.Android.Resource.Id.time = global::App_112GW.Droid.Resource.Id.time;
			global::Xamarin.Forms.Platform.Android.Resource.Id.title = global::App_112GW.Droid.Resource.Id.title;
			global::Xamarin.Forms.Platform.Android.Resource.Id.top = global::App_112GW.Droid.Resource.Id.top;
			global::Xamarin.Forms.Platform.Android.Resource.Id.transition_current_scene = global::App_112GW.Droid.Resource.Id.transition_current_scene;
			global::Xamarin.Forms.Platform.Android.Resource.Id.transition_layout_save = global::App_112GW.Droid.Resource.Id.transition_layout_save;
			global::Xamarin.Forms.Platform.Android.Resource.Id.transition_position = global::App_112GW.Droid.Resource.Id.transition_position;
			global::Xamarin.Forms.Platform.Android.Resource.Id.transition_scene_layoutid_cache = global::App_112GW.Droid.Resource.Id.transition_scene_layoutid_cache;
			global::Xamarin.Forms.Platform.Android.Resource.Id.transition_transform = global::App_112GW.Droid.Resource.Id.transition_transform;
			global::Xamarin.Forms.Platform.Android.Resource.Integer.cancel_button_image_alpha = global::App_112GW.Droid.Resource.Integer.cancel_button_image_alpha;
			global::Xamarin.Forms.Platform.Android.Resource.Integer.status_bar_notification_info_maxnum = global::App_112GW.Droid.Resource.Integer.status_bar_notification_info_maxnum;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.BottomTabLayout = global::App_112GW.Droid.Resource.Layout.BottomTabLayout;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FlyoutContent = global::App_112GW.Droid.Resource.Layout.FlyoutContent;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_action = global::App_112GW.Droid.Resource.Layout.notification_action;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_action_tombstone = global::App_112GW.Droid.Resource.Layout.notification_action_tombstone;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_media_action = global::App_112GW.Droid.Resource.Layout.notification_media_action;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_media_cancel_action = global::App_112GW.Droid.Resource.Layout.notification_media_cancel_action;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_big_media = global::App_112GW.Droid.Resource.Layout.notification_template_big_media;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_big_media_custom = global::App_112GW.Droid.Resource.Layout.notification_template_big_media_custom;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_big_media_narrow = global::App_112GW.Droid.Resource.Layout.notification_template_big_media_narrow;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_big_media_narrow_custom = global::App_112GW.Droid.Resource.Layout.notification_template_big_media_narrow_custom;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_custom_big = global::App_112GW.Droid.Resource.Layout.notification_template_custom_big;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_icon_group = global::App_112GW.Droid.Resource.Layout.notification_template_icon_group;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_lines_media = global::App_112GW.Droid.Resource.Layout.notification_template_lines_media;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_media = global::App_112GW.Droid.Resource.Layout.notification_template_media;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_media_custom = global::App_112GW.Droid.Resource.Layout.notification_template_media_custom;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_part_chronometer = global::App_112GW.Droid.Resource.Layout.notification_template_part_chronometer;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.notification_template_part_time = global::App_112GW.Droid.Resource.Layout.notification_template_part_time;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.RootLayout = global::App_112GW.Droid.Resource.Layout.RootLayout;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.ShellContent = global::App_112GW.Droid.Resource.Layout.ShellContent;
			global::Xamarin.Forms.Platform.Android.Resource.String.status_bar_notification_info_overflow = global::App_112GW.Droid.Resource.String.status_bar_notification_info_overflow;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification = global::App_112GW.Droid.Resource.Style.TextAppearance_Compat_Notification;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Info = global::App_112GW.Droid.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Info_Media = global::App_112GW.Droid.Resource.Style.TextAppearance_Compat_Notification_Info_Media;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::App_112GW.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Line2_Media = global::App_112GW.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2_Media;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Media = global::App_112GW.Droid.Resource.Style.TextAppearance_Compat_Notification_Media;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Time = global::App_112GW.Droid.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Time_Media = global::App_112GW.Droid.Resource.Style.TextAppearance_Compat_Notification_Time_Media;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Title = global::App_112GW.Droid.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Xamarin.Forms.Platform.Android.Resource.Style.TextAppearance_Compat_Notification_Title_Media = global::App_112GW.Droid.Resource.Style.TextAppearance_Compat_Notification_Title_Media;
			global::Xamarin.Forms.Platform.Android.Resource.Style.Widget_Compat_NotificationActionContainer = global::App_112GW.Droid.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Xamarin.Forms.Platform.Android.Resource.Style.Widget_Compat_NotificationActionText = global::App_112GW.Droid.Resource.Style.Widget_Compat_NotificationActionText;
			global::Xamarin.Forms.Platform.Android.Resource.Style.Widget_Support_CoordinatorLayout = global::App_112GW.Droid.Resource.Style.Widget_Support_CoordinatorLayout;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ColorStateListItem = global::App_112GW.Droid.Resource.Styleable.ColorStateListItem;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ColorStateListItem_alpha = global::App_112GW.Droid.Resource.Styleable.ColorStateListItem_alpha;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ColorStateListItem_android_alpha = global::App_112GW.Droid.Resource.Styleable.ColorStateListItem_android_alpha;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ColorStateListItem_android_color = global::App_112GW.Droid.Resource.Styleable.ColorStateListItem_android_color;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CoordinatorLayout = global::App_112GW.Droid.Resource.Styleable.CoordinatorLayout;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CoordinatorLayout_keylines = global::App_112GW.Droid.Resource.Styleable.CoordinatorLayout_keylines;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CoordinatorLayout_statusBarBackground = global::App_112GW.Droid.Resource.Styleable.CoordinatorLayout_statusBarBackground;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CoordinatorLayout_Layout = global::App_112GW.Droid.Resource.Styleable.CoordinatorLayout_Layout;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity = global::App_112GW.Droid.Resource.Styleable.CoordinatorLayout_Layout_android_layout_gravity;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor = global::App_112GW.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_anchor;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity = global::App_112GW.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_anchorGravity;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior = global::App_112GW.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_behavior;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges = global::App_112GW.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_dodgeInsetEdges;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge = global::App_112GW.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_insetEdge;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline = global::App_112GW.Droid.Resource.Styleable.CoordinatorLayout_Layout_layout_keyline;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily = global::App_112GW.Droid.Resource.Styleable.FontFamily;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily_fontProviderAuthority = global::App_112GW.Droid.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily_fontProviderCerts = global::App_112GW.Droid.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::App_112GW.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::App_112GW.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily_fontProviderPackage = global::App_112GW.Droid.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamily_fontProviderQuery = global::App_112GW.Droid.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont = global::App_112GW.Droid.Resource.Styleable.FontFamilyFont;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_android_font = global::App_112GW.Droid.Resource.Styleable.FontFamilyFont_android_font;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_android_fontStyle = global::App_112GW.Droid.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::App_112GW.Droid.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_android_fontWeight = global::App_112GW.Droid.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::App_112GW.Droid.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_font = global::App_112GW.Droid.Resource.Styleable.FontFamilyFont_font;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_fontStyle = global::App_112GW.Droid.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::App_112GW.Droid.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_fontWeight = global::App_112GW.Droid.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.FontFamilyFont_ttcIndex = global::App_112GW.Droid.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor = global::App_112GW.Droid.Resource.Styleable.GradientColor;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor_android_centerColor = global::App_112GW.Droid.Resource.Styleable.GradientColor_android_centerColor;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor_android_centerX = global::App_112GW.Droid.Resource.Styleable.GradientColor_android_centerX;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor_android_centerY = global::App_112GW.Droid.Resource.Styleable.GradientColor_android_centerY;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor_android_endColor = global::App_112GW.Droid.Resource.Styleable.GradientColor_android_endColor;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor_android_endX = global::App_112GW.Droid.Resource.Styleable.GradientColor_android_endX;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor_android_endY = global::App_112GW.Droid.Resource.Styleable.GradientColor_android_endY;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor_android_gradientRadius = global::App_112GW.Droid.Resource.Styleable.GradientColor_android_gradientRadius;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor_android_startColor = global::App_112GW.Droid.Resource.Styleable.GradientColor_android_startColor;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor_android_startX = global::App_112GW.Droid.Resource.Styleable.GradientColor_android_startX;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor_android_startY = global::App_112GW.Droid.Resource.Styleable.GradientColor_android_startY;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor_android_tileMode = global::App_112GW.Droid.Resource.Styleable.GradientColor_android_tileMode;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColor_android_type = global::App_112GW.Droid.Resource.Styleable.GradientColor_android_type;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColorItem = global::App_112GW.Droid.Resource.Styleable.GradientColorItem;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColorItem_android_color = global::App_112GW.Droid.Resource.Styleable.GradientColorItem_android_color;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.GradientColorItem_android_offset = global::App_112GW.Droid.Resource.Styleable.GradientColorItem_android_offset;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int EnterFromLeft = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int EnterFromRight = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ExitToLeft = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ExitToRight = 2130771971;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int alpha = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int coordinatorLayoutStyle = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int font = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int fontProviderAuthority = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int fontProviderCerts = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int fontProviderFetchStrategy = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int fontProviderFetchTimeout = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int fontProviderPackage = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int fontProviderQuery = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int fontStyle = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int fontVariationSettings = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int fontWeight = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int keylines = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int layout_anchor = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int layout_anchorGravity = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int layout_behavior = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int layout_dodgeInsetEdges = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int layout_insetEdge = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int layout_keyline = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int statusBarBackground = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int ttcIndex = 2130837524;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int browser_actions_bg_grey = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int browser_actions_divider_color = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int browser_actions_text_color = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int browser_actions_title_color = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int notification_action_color_filter = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int notification_icon_bg_color = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int notification_material_background_media_default_color = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int primary_text_default_material_dark = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int ripple_material_light = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int secondary_text_default_material_dark = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int secondary_text_default_material_light = 2130903050;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int browser_actions_context_menu_max_width = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int browser_actions_context_menu_min_padding = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int compat_button_inset_horizontal_material = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int compat_button_inset_vertical_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int compat_button_padding_horizontal_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int compat_button_padding_vertical_material = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int compat_control_corner_material = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int compat_notification_large_icon_max_height = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int compat_notification_large_icon_max_width = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_action_icon_size = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_action_text_size = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_big_circle_margin = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notification_content_margin_start = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int notification_large_icon_height = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int notification_large_icon_width = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int notification_main_column_padding_top = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int notification_media_narrow_margin = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int notification_right_icon_size = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int notification_right_side_padding_top = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int notification_small_icon_background_padding = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int notification_small_icon_size_as_large = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int notification_subtext_size = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int notification_top_pad = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int notification_top_pad_large_text = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int subtitle_corner_radius = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int subtitle_outline_width = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int subtitle_shadow_offset = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int subtitle_shadow_radius = 2130968603;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int notification_action_background = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int notification_bg = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int notification_bg_low = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int notification_bg_low_normal = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int notification_bg_low_pressed = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int notification_bg_normal = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int notification_bg_normal_pressed = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int notification_icon_background = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int notification_template_icon_bg = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int notification_template_icon_low_bg = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int notification_tile_bg = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int notify_panel_notification_icon_bg = 2131034124;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060000
			public const int action0 = 2131099648;
			
			// aapt resource value: 0x7F060005
			public const int actions = 2131099653;
			
			// aapt resource value: 0x7F060001
			public const int action_container = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int action_divider = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int action_image = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int action_text = 2131099652;
			
			// aapt resource value: 0x7F060006
			public const int all = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int async = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int blocking = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int bottom = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int bottomtab_navarea = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int bottomtab_tabbar = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int browser_actions_header_text = 2131099660;
			
			// aapt resource value: 0x7F06000F
			public const int browser_actions_menu_items = 2131099663;
			
			// aapt resource value: 0x7F06000D
			public const int browser_actions_menu_item_icon = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int browser_actions_menu_item_text = 2131099662;
			
			// aapt resource value: 0x7F060010
			public const int browser_actions_menu_view = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int cancel_action = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int center = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int center_horizontal = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int center_vertical = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int chronometer = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int clip_horizontal = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int clip_vertical = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int end = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int end_padder = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int fill = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int fill_horizontal = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int fill_vertical = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int flyoutcontent_appbar = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int flyoutcontent_recycler = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int forever = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int ghost_view = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int icon = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int icon_group = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int info = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int italic = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int left = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int line1 = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int line3 = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int main_appbar = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int main_scrollview = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int main_tablayout = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int main_toolbar = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int mask = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int media_actions = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int none = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int normal = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int notification_background = 2131099696;
			
			// aapt resource value: 0x7F060031
			public const int notification_main_column = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int notification_main_column_container = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int parent_matrix = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int right = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int right_icon = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int right_side = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int save_image_matrix = 2131099703;
			
			// aapt resource value: 0x7F060038
			public const int save_non_transition_alpha = 2131099704;
			
			// aapt resource value: 0x7F060039
			public const int save_scale_type = 2131099705;
			
			// aapt resource value: 0x7F06003A
			public const int shellcontent_appbar = 2131099706;
			
			// aapt resource value: 0x7F06003B
			public const int shellcontent_scrollview = 2131099707;
			
			// aapt resource value: 0x7F06003C
			public const int shellcontent_toolbar = 2131099708;
			
			// aapt resource value: 0x7F06003D
			public const int sliding_tabs = 2131099709;
			
			// aapt resource value: 0x7F06003E
			public const int start = 2131099710;
			
			// aapt resource value: 0x7F06003F
			public const int status_bar_latest_event_content = 2131099711;
			
			// aapt resource value: 0x7F060040
			public const int tag_transition_group = 2131099712;
			
			// aapt resource value: 0x7F060041
			public const int tag_unhandled_key_event_manager = 2131099713;
			
			// aapt resource value: 0x7F060042
			public const int tag_unhandled_key_listeners = 2131099714;
			
			// aapt resource value: 0x7F060043
			public const int text = 2131099715;
			
			// aapt resource value: 0x7F060044
			public const int text2 = 2131099716;
			
			// aapt resource value: 0x7F060045
			public const int time = 2131099717;
			
			// aapt resource value: 0x7F060046
			public const int title = 2131099718;
			
			// aapt resource value: 0x7F060047
			public const int toolbar = 2131099719;
			
			// aapt resource value: 0x7F060048
			public const int top = 2131099720;
			
			// aapt resource value: 0x7F060049
			public const int transition_current_scene = 2131099721;
			
			// aapt resource value: 0x7F06004A
			public const int transition_layout_save = 2131099722;
			
			// aapt resource value: 0x7F06004B
			public const int transition_position = 2131099723;
			
			// aapt resource value: 0x7F06004C
			public const int transition_scene_layoutid_cache = 2131099724;
			
			// aapt resource value: 0x7F06004D
			public const int transition_transform = 2131099725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public const int cancel_button_image_alpha = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int status_bar_notification_info_maxnum = 2131165185;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int BottomTabLayout = 2131230720;
			
			// aapt resource value: 0x7F080006
			public const int browser_actions_context_menu_page = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int browser_actions_context_menu_row = 2131230727;
			
			// aapt resource value: 0x7F080001
			public const int FlyoutContent = 2131230721;
			
			// aapt resource value: 0x7F080008
			public const int notification_action = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int notification_action_tombstone = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int notification_media_action = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int notification_media_cancel_action = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int notification_template_big_media = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int notification_template_big_media_custom = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int notification_template_big_media_narrow = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int notification_template_big_media_narrow_custom = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int notification_template_custom_big = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int notification_template_icon_group = 2131230737;
			
			// aapt resource value: 0x7F080012
			public const int notification_template_lines_media = 2131230738;
			
			// aapt resource value: 0x7F080013
			public const int notification_template_media = 2131230739;
			
			// aapt resource value: 0x7F080014
			public const int notification_template_media_custom = 2131230740;
			
			// aapt resource value: 0x7F080015
			public const int notification_template_part_chronometer = 2131230741;
			
			// aapt resource value: 0x7F080016
			public const int notification_template_part_time = 2131230742;
			
			// aapt resource value: 0x7F080002
			public const int RootLayout = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int ShellContent = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int Tabbar = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int Toolbar = 2131230725;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F090000
			public const int ic_launcher = 2131296256;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F0A0000
			public const int ApplicationName = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int Hello = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int library_name = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int status_bar_notification_info_overflow = 2131361795;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0B0000
			public const int AppCompatDialogStyle = 2131427328;
			
			// aapt resource value: 0x7F0B0001
			public const int MainTheme = 2131427329;
			
			// aapt resource value: 0x7F0B0002
			public const int MainTheme_Base = 2131427330;
			
			// aapt resource value: 0x7F0B0003
			public const int TextAppearance_Compat_Notification = 2131427331;
			
			// aapt resource value: 0x7F0B0004
			public const int TextAppearance_Compat_Notification_Info = 2131427332;
			
			// aapt resource value: 0x7F0B0005
			public const int TextAppearance_Compat_Notification_Info_Media = 2131427333;
			
			// aapt resource value: 0x7F0B0006
			public const int TextAppearance_Compat_Notification_Line2 = 2131427334;
			
			// aapt resource value: 0x7F0B0007
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131427335;
			
			// aapt resource value: 0x7F0B0008
			public const int TextAppearance_Compat_Notification_Media = 2131427336;
			
			// aapt resource value: 0x7F0B0009
			public const int TextAppearance_Compat_Notification_Time = 2131427337;
			
			// aapt resource value: 0x7F0B000A
			public const int TextAppearance_Compat_Notification_Time_Media = 2131427338;
			
			// aapt resource value: 0x7F0B000B
			public const int TextAppearance_Compat_Notification_Title = 2131427339;
			
			// aapt resource value: 0x7F0B000C
			public const int TextAppearance_Compat_Notification_Title_Media = 2131427340;
			
			// aapt resource value: 0x7F0B000D
			public const int Widget_Compat_NotificationActionContainer = 2131427341;
			
			// aapt resource value: 0x7F0B000E
			public const int Widget_Compat_NotificationActionText = 2131427342;
			
			// aapt resource value: 0x7F0B000F
			public const int Widget_Support_CoordinatorLayout = 2131427343;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x10101A5,0x101031F,0x7F020000 }
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130837504};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			// aapt resource value: { 0x7F02000C,0x7F020013 }
			public static int[] CoordinatorLayout = new int[] {
					2130837516,
					2130837523};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_keylines = 0;
			
			// aapt resource value: { 0x10100B3,0x7F02000D,0x7F02000E,0x7F02000F,0x7F020010,0x7F020011,0x7F020012 }
			public static int[] CoordinatorLayout_Layout = new int[] {
					16842931,
					2130837517,
					2130837518,
					2130837519,
					2130837520,
					2130837521,
					2130837522};
			
			// aapt resource value: 0
			public const int CoordinatorLayout_Layout_android_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_Layout_layout_anchor = 1;
			
			// aapt resource value: 2
			public const int CoordinatorLayout_Layout_layout_anchorGravity = 2;
			
			// aapt resource value: 3
			public const int CoordinatorLayout_Layout_layout_behavior = 3;
			
			// aapt resource value: 4
			public const int CoordinatorLayout_Layout_layout_dodgeInsetEdges = 4;
			
			// aapt resource value: 5
			public const int CoordinatorLayout_Layout_layout_insetEdge = 5;
			
			// aapt resource value: 6
			public const int CoordinatorLayout_Layout_layout_keyline = 6;
			
			// aapt resource value: 1
			public const int CoordinatorLayout_statusBarBackground = 1;
			
			// aapt resource value: { 0x7F020003,0x7F020004,0x7F020005,0x7F020006,0x7F020007,0x7F020008 }
			public static int[] FontFamily = new int[] {
					2130837507,
					2130837508,
					2130837509,
					2130837510,
					2130837511,
					2130837512};
			
			// aapt resource value: { 0x1010532,0x1010533,0x101053F,0x101056F,0x1010570,0x7F020002,0x7F020009,0x7F02000A,0x7F02000B,0x7F020014 }
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130837506,
					2130837513,
					2130837514,
					2130837515,
					2130837524};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_font = 5;
			
			// aapt resource value: 6
			public const int FontFamilyFont_fontStyle = 6;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontVariationSettings = 7;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontWeight = 8;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x101019D,0x101019E,0x10101A1,0x10101A2,0x10101A3,0x10101A4,0x1010201,0x101020B,0x1010510,0x1010511,0x1010512,0x1010513 }
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: { 0x10101A5,0x1010514 }
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
